/**
 * EasyBeans
 * Copyright (C) 2009 Bull S.A.S.
 * Contact: easybeans@ow2.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307
 * USA
 *
 * --------------------------------------------------------------------------
 * $Id: JNDIResolverRemoteImpl_Stub.java 5369 2010-02-24 14:58:19Z benoitf $
 * --------------------------------------------------------------------------
 */

// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.
package org.ow2.easybeans.component.remotejndiresolver;

public final class JNDIResolverRemoteImpl_Stub extends java.rmi.server.RemoteStub implements
        org.ow2.easybeans.resolver.api.EZBRemoteJNDIResolver {
    private static final long serialVersionUID = 2;

    private static java.lang.reflect.Method $method_getEJBJNDINames_0;

    private static java.lang.reflect.Method $method_getEJBJNDINames_1;

    private static java.lang.reflect.Method $method_getMessageDestinationJNDINames_2;

    static {
        try {
            $method_getEJBJNDINames_0 = org.ow2.easybeans.resolver.api.EZBRemoteJNDIResolver.class.getMethod("getEJBJNDINames",
                    new java.lang.Class[] {java.lang.String.class});
            $method_getEJBJNDINames_1 = org.ow2.easybeans.resolver.api.EZBRemoteJNDIResolver.class.getMethod("getEJBJNDINames",
                    new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
            $method_getMessageDestinationJNDINames_2 = org.ow2.easybeans.resolver.api.EZBRemoteJNDIResolver.class.getMethod(
                    "getMessageDestinationJNDINames", new java.lang.Class[] {java.lang.String.class});
        } catch (java.lang.NoSuchMethodException e) {
            throw new java.lang.NoSuchMethodError("stub class initialization failed");
        }
    }

    // constructors
    public JNDIResolverRemoteImpl_Stub(final java.rmi.server.RemoteRef ref) {
        super(ref);
    }

    // methods from remote interfaces

    // implementation of getEJBJNDINames(String)
    public java.util.List getEJBJNDINames(final java.lang.String $param_String_1) throws java.rmi.RemoteException {
        try {
            Object $result = this.ref.invoke(this, $method_getEJBJNDINames_0, new java.lang.Object[] {$param_String_1},
                    7090994882653366451L);
            return ((java.util.List) $result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of getEJBJNDINames(String, String)
    public java.util.List getEJBJNDINames(final java.lang.String $param_String_1, final java.lang.String $param_String_2)
            throws java.rmi.RemoteException {
        try {
            Object $result = this.ref.invoke(this, $method_getEJBJNDINames_1, new java.lang.Object[] {$param_String_1,
                    $param_String_2}, -1777823870777229803L);
            return ((java.util.List) $result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of getMessageDestinationJNDINames(String)
    public java.util.List getMessageDestinationJNDINames(final java.lang.String $param_String_1)
            throws java.rmi.RemoteException {
        try {
            Object $result = this.ref.invoke(this, $method_getMessageDestinationJNDINames_2,
                    new java.lang.Object[] {$param_String_1}, -6697120795193536734L);
            return ((java.util.List) $result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }
}
