/**
 * EasyBeans
 * Copyright (C) 2009 Bull S.A.S.
 * Contact: easybeans@ow2.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307
 * USA
 *
 * --------------------------------------------------------------------------
 * $Id: RMIServerRPCImpl_Stub.java 5369 2010-02-24 14:58:19Z benoitf $
 * --------------------------------------------------------------------------
 */

// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package org.ow2.easybeans.rpc.rmi.server;

public final class RMIServerRPCImpl_Stub
    extends java.rmi.server.RemoteStub
    implements org.ow2.easybeans.rpc.api.RMIServerRPC
{
    private static final long serialVersionUID = 2;

    private static java.lang.reflect.Method $method_getEJBResponse_0;

    static {
    try {
        $method_getEJBResponse_0 = org.ow2.easybeans.rpc.api.RMIServerRPC.class.getMethod("getEJBResponse", new java.lang.Class[] {org.ow2.easybeans.rpc.api.EJBRemoteRequest.class});
    } catch (java.lang.NoSuchMethodException e) {
        throw new java.lang.NoSuchMethodError(
        "stub class initialization failed");
    }
    }

    // constructors
    public RMIServerRPCImpl_Stub(final java.rmi.server.RemoteRef ref) {
    super(ref);
    }

    // methods from remote interfaces

    // implementation of getEJBResponse(EJBRemoteRequest)
    public org.ow2.easybeans.rpc.api.EJBResponse getEJBResponse(final org.ow2.easybeans.rpc.api.EJBRemoteRequest $param_EJBRemoteRequest_1)
    throws java.rmi.RemoteException
    {
    try {
        Object $result = this.ref.invoke(this, $method_getEJBResponse_0, new java.lang.Object[] {$param_EJBRemoteRequest_1}, -6228114826659083701L);
        return ((org.ow2.easybeans.rpc.api.EJBResponse) $result);
    } catch (java.lang.RuntimeException e) {
        throw e;
    } catch (java.rmi.RemoteException e) {
        throw e;
    } catch (java.lang.Exception e) {
        throw new java.rmi.UnexpectedException("undeclared checked exception", e);
    }
    }
}